### ISSUE TITLE
Lack of authenticated requests

### ISSUE THREAD

**Issue by jmburges** [JackCA/hypem#2]
So I'm looking into modifying the gem to handle authenticated requests. The issue is hypem doesn't reveal any authenticated stuff so I am looking at reverse engineering the javascript.

I am working on a proof of concept set of curl responses, but if I wrote this and submitted for a pull request would you accept it?

I see no better solution since hypem refuses to create and open api. :(

**Comment by JackCA** [comment]
Hey Joe,

There is actually a group of authenticated calls that are available, so there is no need to hack it using Javascript. The problem is that it requires HTTP Basic Authentication, rather than OAuth. Since this is pretty insecure over a non-ssl connection, I chose not to implement it right away.

With authentication, you would be able to validate a user's name/password, love tracks/blogs/searches, see if a user has loved a track, see if a user is friends with another user, and see if a user follows a certain blog.

It's worth noting that these are all legitimate API endpoints, it's just the the documentation for some of them isn't public.

If you'd like access to the private documentation, I would email anthony@hypem.com and tell him you're interested in working on the gem and he'll more than likely shoot it your way.

Let me know if you'd like to chat about this implementation and testing it using VCR.

**Comment by jmburges** [comment]
Oh OK. Yeah thats frustrating because the website uses SSL to login so they
have the SSL certs and everything. Ill email Anthony and see if he has any
plans in making the API https accessible... or doing oauth.

I'd much rather do the proper API calls so ill hit up Anthony and see
what's up.

--Joe Burgess
(703) 402-9206
On Jul 26, 2012 12:05 PM, "Jack Anderson" <
reply@reply.github.com>
wrote:

**Comment by jmburges** [comment]
I emailed him, no response yet. :(

**Comment by jmburges** [comment]
Got a response a while back. Work is slowing down, so I'll start making a stab at this properly.
